### ISSUE TITLE
Release binary

### ISSUE THREAD

**Issue by charles-cooper** [chrisdone/jl#1]
For machines that don't have the utilities / time / memory to build from scratch - I took the liberty of compiling this for linux x86-64 (Ubuntu 16.04), confirmed it runs on a machine without stack or GHC.
[jl.tar.gz](https://github.com/chrisdone/jl/files/1161426/jl.tar.gz)

**Comment by chrisdone** [comment]
That's cool @charles-cooper! I was thinking of setting up some automation to build these on git tags for distributions, via travis releases https://docs.travis-ci.com/user/deployment/releases/

**Comment by chrisdone** [comment]
https://github.com/chrisdone/jl/releases

**Comment by charles-cooper** [comment]
That was quite the turnaround time!
