### ISSUE TITLE
Object entries

### ISSUE THREAD

**Issue by devmckeon** [chrisdone/jl#15]
I am not seeing (toEntries/fromEntries) equivalents, to create/merge a list of key-value tuples from/to a JSON object. Does this exist and I'm just not seeing it (not doing it manually, as that's a lot of boilerplate for folding over an object, and not just keys or values), is it planned?

The way I see to do this currently is: 

toEntries
`echo '{"a":1, "b":2, "c":3}' | jl "\o -> map (\k -> [k, o[k]]) $ keys o"`
`[["a",1],["b",2],["c",3]]`

fromEntries
`echo '[["a",1],["b",2],["c",3]]' | jl "fold (\o kv -> set kv[0] kv[1] o) {}"`
`{"a":1, "b":2, "c":3}`

And that is a lot of boilerplate if I want to map the keys and vals:
`echo '{"a":1, "b":2, "c":3}' | jl "(\o -> map ( \k -> [k, o[k]]) $ keys o ) | map (\kv -> [ kv[0], kv[1] + 1]) | fold (\o kv -> set kv[0] kv[1] o) {}"`
`{"a":2, "b":3, "c":4}`

Compared to: 
`echo '{"a":1, "b":2, "c":3}' | jl "toEntries | map (\kv -> [ kv[0], kv[1] + 1]) | fromEntries"`

Also would be nice to have a dedicated map fn:
`echo '{"a":1, "b":2, "c":3}' | jl "mapEnts (\kv -> [ kv[0], kv[1] + 1])"`

Possible names:
object to entries: toEntries, toEnts, ents, o2kv, 
entries to object: fromEntries, fromEnts, obj, kv2o, setAll

**Comment by chrisdone** [comment]
Right, perhaps we need `map` to work over an object, like `Data.Map.map`, and `mapWithKey` for the equivalent `Data.Map.mapWithKey`. 

The `fromEntries` and `toEntries` are very likely to be use-case specific and depend on the schema of the JSON a person is dealing with, and the `map` or `fold` needed to achieve a once off translation seems to be low overhead.
