### ISSUE TITLE
Cannot access object keys starting with a capital letter

### ISSUE THREAD

**Issue by patrickherrmann** [chrisdone/jl#2]
It looks like variable names cannot start with a capital letter, which makes sense for lambdas like `\x -> x`. However this means that keys that start with a capital letter cannot be accessed, resulting in an error during tokenization.
```
echo '{ "Foo": 5 }' | jl '_.Foo'
```

**Comment by chrisdone** [comment]
Fixed! 

```
bash-3.2$ echo '{ "Foo": 5 }' | jl '_.Foo'
5
```

And if you have non-alphanumeric keys you can use 

```haskell
bash-3.2$ echo '{ "Foo": 5 }' | jl '_["Foo"]'
5
```

**Comment by patrickherrmann** [comment]
Wonderful, thanks!
