### ISSUE TITLE
Add an if statement

### ISSUE THREAD

**Issue by axman6** [chrisdone/jl#5]
It'd be great to have an if statement so decisions can be made - I have a use case where I need to decide whether to return the current object or one of its children based on some information in that object. I guess the standard Haskell syntax of `if ... then ... else ...` would would well, or a `bool` function (not sure if the Data.Bool catamorphism order of arguments is the most logical here, `bool cond truecase falsecase` feels like it'd be more familiar.)

**Comment by chrisdone** [comment]
There's support for that, but looks like I didn't document it in the readme!
```haskell
$ echo '{"1":1, "a":2}' | jl '\x->if x.1 = 1 then "yay" else "boo"'
"yay"
```

**Comment by chrisdone** [comment]
Added docs to the README.

**Comment by axman6** [comment]
Fantastic, thanks Chris!
