### ISSUE TITLE
Support for a sequence of whitespace-separated JSON values.

### ISSUE THREAD

**Issue by qzchenwl** [chrisdone/jl#7]
> jq filters run on a stream of JSON data. The input to jq is parsed as a sequence of whitespace-separated JSON values which are passed through the provided filter one at a time. The output(s) of the filter are written to standard out, again as a sequence of whitespace-separated JSON data.

Reading from a stream which outputs JSON values continuously and transform each value then output to stdout is quite useful.

I have a script running:
```bash
some-porgram | jq 'my filter program' > output.txt
```

I prefer `jl`'s syntax a lot. Looking for a way to switch to `jl`.

**Comment by chrisdone** [comment]
That's pretty easily doable with Aeson's parsing functions. 👍
