### ISSUE TITLE
unexpected “data”: that keyword isn't allowed

### ISSUE THREAD

**Issue by przemek-pokrywka** [chrisdone/jl#8]
Running:
`echo '{"data": 1}' | jl '_.data'`
results in:
```
jl: TokenizerError (line 1, column 7):
unexpected “data”: that keyword isn't allowed, but you could use this instead: data_
```
while it would be good to have an ability to use `"data"` as JSON field name.

**Comment by chrisdone** [comment]
Right, I'll remove those keyword checks as they're only relevant for Haskell, not this smaller language.

**Comment by chrisdone** [comment]
I've bumped this as version 0.0.3. There'll be a binary release uploaded automatically when the CI finishes: https://travis-ci.org/chrisdone/jl/builds/265119872
