### ISSUE TITLE
Pretty Printing

### ISSUE THREAD

**Issue by justanotherdot** [chrisdone/jl#9]
Love the tool, thanks for all the effort in making it!

I was curious if `jl` has any pretty printing functionality akin to `jq`? I know this is a bit opinionated but I thought I'd ask to see if it's a non-goal or not for the project. Maybe something like `pprint` could be added possibly?

**Comment by chrisdone** [comment]
Yep it's -p or --pretty in the commandline flags

**Comment by justanotherdot** [comment]
Ah, I missed that in `--help`. Thanks!
